### PR TITLE
initial macOS packaging

### PR DESCRIPTION
**Pull request by mfkl**

### CODE REVIEW

**Comment by mfkl** [comment]
- packaging the dylibs inside the `.app` bundle with correct folder hierarchy is currently an issue with the `.targets` file.
- some dylibs are different than others, from my understanding. `libvlc` and `libvlccore` ones are different than the plugins dylib and should be setup differently.

**Comment by mfkl** [comment]
Bundling the dylibs inside the .app bundle works, but P/Invoke into them is still an issue... something to do with @rpath stuff probably.

**Comment by jeremyVignelles** [comment]
Can you be more specific? is there an error message?

**Comment by mfkl** [comment]
I'll have a second look soon and let you know.

**Comment by mfkl** [comment]
Hitting 
```
System.DllNotFoundException: Could not find the runtime library libxammac.dylib
```
When doing a P/Invoke with
```
<configuration>
    <dllmap dll="libvlc" target="@executable_path/lib/libvlc.5.dylib"/>
</configuration>
```
No idea if the paths are wrong or I'm missing other steps entirely... (dylib remapping or else)

**Pull request merged**
